import { Body, Controller, Delete, Get, Param, Patch, Post, Query, Req } from '@nestjs/common';
import { ApiBearerAuth, ApiBody, ApiOperation, ApiQuery, ApiTags } from '@nestjs/swagger';
import { Public, Roles } from 'src/common/decorator/rolesDecorator';
import { AddProductImageDto } from '../dto/add-product-image.dto';
import { CreateProductDto } from '../dto/create-product.dto';
import { ProductListQueryDto } from '../dto/product-list-query.dto';
import { UpdateProductDto } from '../dto/update-product.dto';
import { UpdateProductImageDto } from '../dto/update-product-image.dto';
import { UpdateProductStatusDto } from '../dto/update-product-status.dto';
import { UpdateProductStockDto } from '../dto/update-product-stock.dto';
import { StoreProductsService } from './products.service';

@ApiTags('Store - Products')
@ApiBearerAuth('bearer')
@Controller()
export class StoreProductsController {
  constructor(private readonly productsService: StoreProductsService) {}

  @Post('products')
  @Roles('ADMIN', 'STAFF')
  @ApiOperation({ summary: 'Create product (SKU generated by backend)' })
  @ApiBody({ type: CreateProductDto })
  createProduct(@Body() dto: CreateProductDto, @Req() req?: { user?: { id: string; role: string } }) {
    return this.productsService.createProduct(dto, req?.user);
  }

  @Get('products')
  @Public()
  @ApiOperation({ summary: 'Public/customer product list with filters' })
  @ApiQuery({ name: 'page', required: false, type: Number })
  @ApiQuery({ name: 'limit', required: false, type: Number })
  @ApiQuery({ name: 'search', required: false, type: String })
  @ApiQuery({ name: 'categoryId', required: false, type: String })
  @ApiQuery({ name: 'subCategoryId', required: false, type: String })
  @ApiQuery({ name: 'taxable', required: false, enum: ['TAXABLE', 'NON_TAXABLE'] })
  @ApiQuery({ name: 'isActive', required: false, type: Boolean })
  @ApiQuery({ name: 'status', required: false, enum: ['DRAFT', 'ACTIVE', 'INACTIVE', 'ARCHIVED'] })
  @ApiQuery({ name: 'minPrice', required: false, type: Number })
  @ApiQuery({ name: 'maxPrice', required: false, type: Number })
  @ApiQuery({ name: 'stockState', required: false, enum: ['inStock', 'outOfStock'] })
  @ApiQuery({ name: 'sortBy', required: false, enum: ['createdAt', 'updatedAt', 'name', 'price'] })
  @ApiQuery({ name: 'sortOrder', required: false, enum: ['asc', 'desc'] })
  listProducts(@Query() query: ProductListQueryDto, @Req() req?: { user?: { id: string; role: string } }) {
    return this.productsService.listProducts(query, req?.user);
  }

  @Get('products/admin/list')
  @Roles('ADMIN', 'STAFF')
  @ApiOperation({ summary: 'Admin product list with full visibility' })
  getAdminProductList(@Query() query: ProductListQueryDto, @Req() req?: { user?: { id: string; role: string } }) {
    return this.productsService.getAdminProducts(query, req?.user);
  }

  @Get('products/:id')
  @Public()
  @ApiOperation({ summary: 'Get product details by id' })
  getProductById(@Param('id') id: string, @Req() req?: { user?: { id: string; role: string } }) {
    return this.productsService.getProductById(id, req?.user);
  }

  @Patch('products/:id')
  @Roles('ADMIN', 'STAFF')
  @ApiOperation({ summary: 'Update product' })
  @ApiBody({ type: UpdateProductDto })
  updateProduct(
    @Param('id') id: string,
    @Body() dto: UpdateProductDto,
    @Req() req?: { user?: { id: string; role: string } },
  ) {
    return this.productsService.updateProduct(id, dto, req?.user);
  }

  @Delete('products/:id')
  @Roles('ADMIN', 'STAFF')
  @ApiOperation({ summary: 'Delete/deactivate product safely' })
  deleteProduct(@Param('id') id: string, @Req() req?: { user?: { id: string; role: string } }) {
    return this.productsService.deleteProduct(id, req?.user);
  }

  @Patch('products/:id/status')
  @Roles('ADMIN', 'STAFF')
  @ApiOperation({ summary: 'Quick product status update' })
  updateProductStatus(
    @Param('id') id: string,
    @Body() dto: UpdateProductStatusDto,
    @Req() req?: { user?: { id: string; role: string } },
  ) {
    return this.productsService.updateProductStatus(id, dto, req?.user);
  }

  @Patch('products/:id/stock')
  @Roles('ADMIN', 'STAFF')
  @ApiOperation({ summary: 'Update product stock quantity' })
  updateProductStock(
    @Param('id') id: string,
    @Body() dto: UpdateProductStockDto,
    @Req() req?: { user?: { id: string; role: string } },
  ) {
    return this.productsService.updateProductStock(id, dto, req?.user);
  }

  @Post('products/:id/images')
  @Roles('ADMIN', 'STAFF')
  @ApiOperation({ summary: 'Add product image URL' })
  addProductImage(@Param('id') id: string, @Body() dto: AddProductImageDto, @Req() req?: { user?: { id: string; role: string } }) {
    return this.productsService.addProductImage(id, dto, req?.user);
  }

  @Patch('products/:id/images/:imageId')
  @Roles('ADMIN', 'STAFF')
  @ApiOperation({ summary: 'Update product image metadata' })
  updateProductImage(
    @Param('id') id: string,
    @Param('imageId') imageId: string,
    @Body() dto: UpdateProductImageDto,
    @Req() req?: { user?: { id: string; role: string } },
  ) {
    return this.productsService.updateProductImage(id, imageId, dto, req?.user);
  }

  @Delete('products/:id/images/:imageId')
  @Roles('ADMIN', 'STAFF')
  @ApiOperation({ summary: 'Delete product image' })
  deleteProductImage(
    @Param('id') id: string,
    @Param('imageId') imageId: string,
    @Req() req?: { user?: { id: string; role: string } },
  ) {
    return this.productsService.deleteProductImage(id, imageId, req?.user);
  }
}

